name: 'test2'
description: 'Greet someone'
runs:
  using: 'composite'
  steps:
     - name: Checkout Repository
       uses: actions/checkout@v3.3.0
    
     - name: test
       run: echo "estou no diretorio teste2"
       shell: bash