name: 'test'
description: 'Greet someone'
runs:
  using: 'composite'
  steps:
     - name: Checkout Repository
       uses: actions/checkout@v3.3.0
    
     - name: test
       run: echo "estou no arquivo action.yml"
       shell: bash
