name: Reusable workflow example

on:
    workflow_call:
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set credentials aws
      run: echo "estou no arquivo test2.yml"