name: Usando compartilhado
on:
  workflow_dispatch:
jobs:
   triage:
     runs-on: ubuntu-latest
     steps:
     - name: set credentials aws
       uses: joaov-barbosa/sharing-workflow-demo/.github/workflows/sharing/test.yml@mig