name: Usando compartilhado
on: workflow_dispatch
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: test caminho
     run: ls -lha
   - uses: ./.github/actions/teste
     with:
      aws-region: ${{ vars.AWS_REGION }}
      aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   - uses: ./.github/actions/teste2