name: Usando compartilhado
on: workflow_dispatch
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: test caminho
     run: ls -lha
   - name: test workflow
     uses: ./.github/actions/teste