name: Usando compartilhado
on: workflow_dispatch
jobs:
  test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v3

   - name: test caminho
     run: ls -lha
   - uses: ./.github/actions/teste
   - uses: ./.github/actions/teste2